# Generated by Django 5.2 on 2026-01-18 06:27

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Trade",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("broker_id", models.CharField(max_length=100)),
                (
                    "direction",
                    models.CharField(
                        choices=[("BUY", "Buy"), ("SELL", "Sell")], max_length=4
                    ),
                ),
                ("symbol", models.CharField(max_length=10)),
                (
                    "entry_time",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("entry_price", models.FloatField()),
                ("exit_time", models.DateTimeField(blank=True, null=True)),
                ("exit_price", models.FloatField(blank=True, null=True)),
                (
                    "exit_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("TP", "Take Profit"),
                            ("SL", "Stop Loss"),
                            ("MANUAL", "Manual"),
                            ("LIQUIDATION", "Liquidation"),
                            ("OTHER", "Other"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                ("order_volume", models.FloatField(blank=True, null=True)),
                ("sl", models.FloatField(blank=True, null=True)),
                ("tp", models.FloatField(blank=True, null=True)),
                ("session", models.CharField(blank=True, max_length=50, null=True)),
                ("pnl", models.FloatField(blank=True, null=True)),
                ("capital", models.FloatField()),
                ("leverage", models.FloatField(default=500)),
                ("strategy", models.CharField(max_length=50)),
                ("broker", models.CharField(max_length=50)),
                (
                    "market_type",
                    models.CharField(
                        choices=[
                            ("FOREX", "Forex"),
                            ("CRYPTO", "Crypto"),
                            ("OTHER", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "timeframe",
                    models.CharField(
                        choices=[
                            ("1M", "1 Minute"),
                            ("5M", "5 Minutes"),
                            ("15M", "15 Minutes"),
                            ("1H", "1 Hour"),
                            ("4H", "4 Hours"),
                            ("1D", "1 Day"),
                        ],
                        max_length=50,
                    ),
                ),
                ("synched", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="TradeClosePricesMutation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mutation_time", models.DateTimeField(auto_now_add=True)),
                ("mutation_price", models.FloatField(blank=True, null=True)),
                ("new_tp_price", models.FloatField(blank=True, null=True)),
                ("new_sl_price", models.FloatField(blank=True, null=True)),
                ("pnl_at_new_tp_price", models.FloatField(blank=True, null=True)),
                ("pnl_at_new_sl_price", models.FloatField(blank=True, null=True)),
                (
                    "trade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="close_prices_mutations",
                        to="trades.trade",
                    ),
                ),
            ],
            options={
                "verbose_name": "Trade Close Prices Mutation",
                "verbose_name_plural": "Trade Close Prices Mutations",
                "ordering": ["mutation_time"],
            },
        ),
    ]
