# Generated by Django 5.2 on 2025-11-30 15:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='entry_time',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
