# Generated by Django 5.2 on 2026-01-18 06:10

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0002_alter_trade_entry_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trade',
            old_name='transaction_broker_id',
            new_name='broker_id',
        ),
        migrations.RenameField(
            model_name='trade',
            old_name='type',
            new_name='direction',
        ),
        migrations.RenameField(
            model_name='trade',
            old_name='close_price',
            new_name='exit_price',
        ),
        migrations.RenameField(
            model_name='trade',
            old_name='closing_reason',
            new_name='exit_reason',
        ),
        migrations.RenameField(
            model_name='trade',
            old_name='close_time',
            new_name='exit_time',
        ),
        migrations.RenameField(
            model_name='trade',
            old_name='max_drawdown',
            new_name='sl',
        ),
        migrations.RenameField(
            model_name='trade',
            old_name='max_profit',
            new_name='tp',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='break_even_price',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='liquidity_price',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='order_commission',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='pnl_excluding_commission',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='position_size_usd',
        ),
        migrations.AddField(
            model_name='trade',
            name='session',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='synched',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='trade',
            name='entry_time',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='trade',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
