# Generated by Django 5.2 on 2026-04-16 15:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trades", "0004_add_environment_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
