groups:
    - name: log-rules
      rules:
        - alert: HighLogErrorRate
          expr: sum(rate({job="containerlogs"} |~ "(?i)error"[1m])) by (container) > 1
          for: 1m
          labels:
            severity: critical
          annotations:
            description: 'High error rate in container {{ $labels.container }}.'
            summary: High error rate detected in logs
